-- Migration: Add tenant_id and is_seed columns to m_cat_blocks
-- Description: Enables per-tenant catalog block scoping and marks blocks
--              that were auto-generated during onboarding seed.
--              The edge function (cat-blocks/index.ts) already references
--              these columns — this migration ensures they exist idempotently.
-- Date: 2026-05-21

-- ============================================================================
-- ADD COLUMNS (idempotent)
-- ============================================================================

ALTER TABLE "public"."m_cat_blocks"
    ADD COLUMN IF NOT EXISTS "tenant_id" UUID,
    ADD COLUMN IF NOT EXISTS "is_seed"   BOOLEAN NOT NULL DEFAULT false;

-- ============================================================================
-- INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS "idx_cat_blocks_tenant_id"
    ON "public"."m_cat_blocks" ("tenant_id");

-- Composite: tenant + live + active (used by onboarding and catalog-studio reads)
CREATE INDEX IF NOT EXISTS "idx_cat_blocks_tenant_live_active"
    ON "public"."m_cat_blocks" ("tenant_id", "is_live", "is_active")
    WHERE "is_active" = true;

-- Seed blocks lookup (used by Screen 8A pre-populate)
CREATE INDEX IF NOT EXISTS "idx_cat_blocks_tenant_seed"
    ON "public"."m_cat_blocks" ("tenant_id", "is_seed")
    WHERE "is_seed" = true;

-- ============================================================================
-- RLS UPDATE
-- ============================================================================
-- Tenants must be able to read their own seed blocks (is_live=false during review).
-- Existing read policy only allows active+visible global blocks.
-- We extend it to include the tenant's own blocks.

DROP POLICY IF EXISTS "read_cat_blocks" ON "public"."m_cat_blocks";

CREATE POLICY "read_cat_blocks"
    ON "public"."m_cat_blocks"
    FOR SELECT
    USING (
        -- Global KT blocks (visible to all authenticated users)
        ("tenant_id" IS NULL AND "is_active" = true AND "visible" = true)
        OR
        -- Seed blocks visible to all authenticated (used in catalog preview)
        ("is_seed" = true AND "is_active" = true)
        OR
        -- Tenant's own blocks
        ("tenant_id" = (auth.jwt() ->> 'tenant_id')::uuid)
        OR
        -- Admin sees everything
        ((auth.jwt() ->> 'is_admin')::boolean = true)
    );

-- ============================================================================
-- COMMENTS
-- ============================================================================

COMMENT ON COLUMN "public"."m_cat_blocks"."tenant_id"
    IS 'NULL = global KT block (master data). UUID = tenant-scoped block created during onboarding or by tenant.';

COMMENT ON COLUMN "public"."m_cat_blocks"."is_seed"
    IS 'True when block was auto-generated by seedTenantOnIndustryConfirmed during onboarding. Tenant reviews and confirms these on Screen 8A.';
